import Provider from "./components/Provider";
import "./globals.css";
import { Noto_Sans } from "next/font/google";

const noto_sans = Noto_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-screen w-screen" lang="en">
      <body className={noto_sans.className + " h-full w-full"}>
        <Provider>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
